# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curva.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon

from asme.asme_vii_div2_curve import AsmeCurves as am
from asme.asme_vii_div2_curve import mat

from qt_layout.main_ui import Ui_MainWindow



class Main_MainWindow(Ui_MainWindow):
    def __init__(self):
        super(Main_MainWindow, self).__init__()

    def plotcurve(self):
        am.true_stress_strain_curve_aco('SA-240 TP304', False)

    def downloadcurve(self):
        am.true_stress_strain_curve_aco('SA-240 TP304', True)

    def printcurve(self):
        am.local_failure_strain_limit()
 

def window():   
    app = QtWidgets.QApplication([])
    window = QtWidgets.QMainWindow()
    ui = Main_MainWindow()
    ui.setupUi(window)
    window.show()
    app.exec()

window()

