# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Elastoplastico = QtWidgets.QGroupBox(self.centralwidget)
        self.Elastoplastico.setGeometry(QtCore.QRect(10, 20, 141, 191))
        self.Elastoplastico.setObjectName("Elastoplastico")
        self.btn1 = QtWidgets.QPushButton(self.Elastoplastico)
        self.btn1.setGeometry(QtCore.QRect(10, 30, 93, 28))
        self.btn1.setObjectName("btn1")
        self.btn3 = QtWidgets.QPushButton(self.Elastoplastico)
        self.btn3.setGeometry(QtCore.QRect(10, 150, 93, 28))
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.Elastoplastico)
        self.btn2.setGeometry(QtCore.QRect(10, 90, 93, 28))
        self.btn2.setObjectName("btn2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 260, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(360, 0, 20, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(390, 0, 401, 251))
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(610, 301, 171, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(200, 20, 141, 191))
        self.groupBox.setObjectName("groupBox")
        self.Material = QtWidgets.QComboBox(self.groupBox)
        self.Material.setGeometry(QtCore.QRect(10, 30, 81, 22))
        self.Material.setObjectName("Material")
        self.Material.addItem("")
        self.Material.addItem("")
        self.Material.addItem("")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 80, 95, 20))
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn1.clicked.connect(self.plotcurve)
        self.btn2.clicked.connect(self.downloadcurve)
        self.btn3.clicked.connect(self.printcurve)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Elastoplastico.setTitle(_translate("MainWindow", "Elastoplastico"))
        self.btn1.setText(_translate("MainWindow", "Curva"))
        self.btn3.setText(_translate("MainWindow", "print"))
        self.btn2.setText(_translate("MainWindow", "download"))
        self.groupBox.setTitle(_translate("MainWindow", "Material"))
        self.Material.setItemText(0, _translate("MainWindow", "aco inox"))
        self.Material.setItemText(1, _translate("MainWindow", "aco carbono"))
        self.Material.setItemText(2, _translate("MainWindow", "aluminio"))
        self.radioButton.setText(_translate("MainWindow", "mecanicas"))
